# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20151113_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_1',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_10',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_11',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_12',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_13',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_14',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_15',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_16',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_17',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_18',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_19',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_2',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_20',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_21',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_22',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_23',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_24',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_25',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_26',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_27',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_28',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_29',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_3',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_30',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_31',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_4',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_5',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_6',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_7',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_8',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day_9',
        ),
    ]
