# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20151113_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_21',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_22',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_23',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_25',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_26',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_27',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_28',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_29',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_31',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day_9',
            field=models.BooleanField(default=False),
        ),
    ]
